### ISSUE TITLE
Python 2 bindings not generated on Debian

### ISSUE THREAD

**Issue by stationarysalesman** [SynBioDex/libSBOL#144] opened 2017-03-03 02:10 UTC
Generating Python wrappers for libSBOL does not work out of the box on a fresh Debian VM. Building the wrappers generates this error:
`/home/tyler/Documents/research/sbol/libSBOL/source/config.h:51: Error: Syntax error in input(3)`
which appears to be caused by the compiler (or swig?) being unable to correctly parse double angle brackets.

**Comment by stationarysalesman** [comment] 2017-03-03 02:25
After installing SWIG 3 (default with distro is 2), linker error followed:
```c
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/4.9/../../../x86_64-linux-gnu/libraptor2.a(raptor_parse.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/lib/gcc/x86_64-linux-gnu/4.9/../../../x86_64-linux-gnu/libraptor2.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
```

**Comment by kirichoi** [comment] 2017-03-03 02:32
Sorry for the inconvenience. I presume after updating to SWIG 3.0+ the first issue is gone?
For the second issue, we are actually aware of it and devising a solution. The problem is caused from the fact that some of the dependencies, namely jsoncpp and raptor2, provides static libraries without PIC support, which is necessary when compiling shared libraries (i.e. Python binaries) out of static libraries.
As a workaround, I suggest you to compile shared version of libSBOL and generate pySBOL out of it instead. It will work perfectly fine in a machine that it's compiled as the shared version of dependencies will already be present in the environment.

**Comment by stationarysalesman** [comment] 2017-03-03 19:37
Yeah I figured it was an issue with raptor or something, I'll try it out and write back with any problems.

**Comment by stationarysalesman** [comment] 2017-03-03 23:29
So it seems that building SBOL as a shared library (without generating Python wrappers) also generates this error:
```c
Linking CXX shared library /home/tyler/Documents/research/sbol/libSBOL/release/library/lib/libsbol.so
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/4.9/../../../x86_64-linux-gnu/libraptor2.a(raptor_parse.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/lib/gcc/x86_64-linux-gnu/4.9/../../../x86_64-linux-gnu/libraptor2.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
```

However, building the static version of SBOL (without building the Python wrappers) seems to work ok.

**Comment by kirichoi** [comment] 2017-03-04 00:49
It seems like for some reason, you are still using static version of libraptor2. I presume you ticked off SBOL_BUILD_SHARED in CMake? If so, I will look into the script to fix the issue. In the meantime, you can manually change the path to dependencies to the shared variant (e.g. libraptor2.so under the same folder as .a)

**Comment by kirichoi** [comment] 2017-03-04 01:16
Confirmed the issue. Fix is coming soon.

**Comment by bbartley** [comment] 2017-03-04 01:21
Following up on what Kiri said, you can direct CMake to link the dynamic library by specifying -DRAPTOR_LIBRARY= /usr/lib/x86_64-linux-gnu/libraptor2.so at the CMake commandline

(You might want to double-check that path, but you get the idea)

**Comment by kirichoi** [comment] 2017-03-04 02:08
Commit 19136b6e7a0c1b530fd27ca0f26f02d43df43430 should have fixed any issues related to building python wrappers out of shared libSBOL on linux/unix environment. Changes are merged to master branch,

**Comment by kirichoi** [comment] 2017-07-06 00:12
Commit d2a8d1ef366b380f49838118f276bf8c9c436ebc further fixes this issue. Manylinux distro for pySBOL is planned, and will be tracked on https://github.com/SynBioDex/pySBOL/issues/13.

**Closed as completed by kirichoi** 2017-07-06 00:12 UTC
Labels: Bug, Urgent, Priority
